### ISSUE TITLE
Generating RDF Collections 

### ISSUE THREAD

**Issue by dachafra** [kg-construct/mapping-challenges#10]
issue:  not possible to generate RDF Collections and Containers

suggestion: extend RML with ability to generate RDF Collections and Containers. See e.g. xR2RML. Particularly useful for metamodel and schema-level transformations where lists are often used.

**Comment by frmichel** [comment]
Regarding RDF lists and containers, here are a few pointers to the [specification](http://i3s.unice.fr/~fmichel/xr2rml_specification.html) of the xR2RML mapping language in which we addressed this question. The idea is to use "nested term maps", that is term maps within term maps, together with new term types  for RDF list, bag, seq and alt.

Some examples are in sections [2.5](http://i3s.unice.fr/~fmichel/xr2rml_specification.html#_Toc466307455) and [2.6](http://i3s.unice.fr/~fmichel/xr2rml_specification.html#_Toc466307456). 
Section 3 describes this more formally in [3.2.2.5](http://i3s.unice.fr/~fmichel/xr2rml_specification.html#_Toc466307471) and [3.2.3](http://i3s.unice.fr/~fmichel/xr2rml_specification.html#_Toc466307472).

**Comment by chrdebru** [comment]
The work of [Lucy McKenna](https://link.springer.com/chapter/10.1007%2F978-3-319-67008-9_42) required looking at that as well. However, the collections that needed to be generated requires a mix of term types. It proposes constructs to collect term types across rows and across columns, with the latter providing support for mixing term types.

**Comment by dachafra** [comment]
@chrdebru and @frmichel are currently working on a solution for this, so we can close it
