### ISSUE TITLE
Group TripleMaps for Performance

### ISSUE THREAD

**Issue by dachafra** [kg-construct/mapping-challenges#12]
issue: running each source row through each TripleMap may be slow because it means "rewinding" the database and processing each row multiple times

suggestion: process all TripleMaps with the same (or equivalent source) for each input row

link: https://github.com/SDM-TIB/SDM-RDFizer/issues/24#issuecomment-648665289

**Comment by marioscrock** [comment]
I think this is more a tool-related optimization, however, I would suggest considering also joins conditions in the process of grouping TripleMaps for performance. This type of analysis (considering join "dependencies" among TripleMaps) could also help in enabling efficient concurrency in the processing of groups of not-constrained TripleMaps.

**Comment by dachafra** [comment]
This issue is out of the scope of the CG, as it's specific for the optimizations of each tool. Closing it

**Comment by dachafra** [comment]
I agree that we can generate a `Best practices` repository where we collaboratively post well-known optimizations or techniques to speed up the materialization process. @bjdmeest would you mind to create that repo under the organization?

**Comment by bjdmeest** [comment]
Done at https://github.com/kg-construct/best-practices, with a first issue! :D
