### ISSUE TITLE
Challenge: Nested cells in CSV

### ISSUE THREAD

**Issue by ghost** [kg-construct/mapping-challenges#19]
From stackoverflow: https://stackoverflow.com/questions/61751174/is-there-a-solution-in-rml-for-multiple-complex-entities-in-one-data-element-ce 
# Description
For nested CSV cells, it is possible to split the values with an FnO function, but it is not possible to refer to these values individually with a referencing object map. Instead, the referencing object map points to the cell containing all nested values, and as a result all subcells are used as object, instead of one specific subcell.
# Input data (csv)
```csv
Person
"Wilson, Charles; Harris Arthur"
"White, D.
Arthur Harris"
```
# Desired output
```ttl
:Wilson a foaf:Person;
    foaf:firstName "Charles";
    foaf:lastName "Wilson" .

:Harris a foaf:Person;
    foaf:firstName "Arthur";
    foaf:lastName "Harris" .

:White a foaf:Person;
    foaf:firstName "D.";
    foaf:lastName "White" .
```

**Comment by dachafra** [comment]
This has been already moved to https://github.com/kg-construct/rml-fno-spec/issues/13 
So we can close it
