### ISSUE TITLE
Clarify multi-valued term maps

### ISSUE THREAD

**Issue by dachafra** [kg-construct/mapping-challenges#4]
issue: RML spec not clear on how to handle multi-valued term maps

suggestion: clarify spec on how to handle multi-valued term maps (multiple results for term generating functions)

**Comment by pmaria** [comment]
Discussion in  RMLio/rmlmapper-java#28 also relevant for this issue.

**Comment by VladimirAlexiev** [comment]
https://github.com/RMLio/rml-implementation-report/issues/11
https://github.com/carml/carml/issues/52

**Comment by dachafra** [comment]
This has already been tackled in the work of containers and collections. We close it
